### ISSUE TITLE
v2.10.3 get_user_info 使用 uid 无法查询

### ISSUE THREAD

**Issue by single-ptilopsis** [Starry-OvO/Tieba-Cloud-Review#81]
**如何复现**

test.py
```python
import asyncio

import aiotieba as tb


async def run():
    async with tb.Client() as client:
        user = await client.get_user_info(809141539)
        print(user)
        print(user.user_id)


loop = asyncio.get_event_loop()
loop.run_until_complete(run())
```
aiotieba.toml
```toml
[User]

# default是自定义的BDUSS_key，你可以改成你喜欢的标识
# 该设计是为了方便通过BDUSS_key快速调用BDUSS，这样你就不用每次都填一串很长的东西作为参数
[User.default]
BDUSS = "" # 把你的那一串长长的BDUSS放在这
```
`python 3.9` `v2.10.3`
```python
<2023-01-13 15:30:51.254> [WARN] [_get_uinfo_getUserInfo] (110000, '请先登录'). user=809141539
<2023-01-13 15:30:51.254> [WARN] [get_user_info] Null input
0
0
```
`python 3.9` `v2.9.1`
```python
雪景suki
809141539
```
**你希望程序作出何种行为**
如 `v2.9.1` 所示
